### ISSUE TITLE
bundle

### ISSUE THREAD

**Issue by munrocket** [davidmartinez10/bigfloat#1]
Please create web bundle of your library that can be cached by jsdelivr.com and unpkg.com CDNs

**Comment by davidmartinez10** [comment]
> Please create web bundle of your library that can be cached by jsdelivr.com and unpkg.com CDNs

Sure. What are you using it for? Just curious.

**Comment by munrocket** [comment]
For fractal render. Just curious how fast and precise it works.

**Comment by davidmartinez10** [comment]
> For fractal render. Just curious how fast and precise it works.

Hi, @munrocket. Sorry for my late response. I have been through surgery and I had to leave this project aside for some time. But I have done as you requested. Better late than never.

Check it out:
https://unpkg.com/browse/bigfloat.js@2.0.2/lib/

**Comment by munrocket** [comment]
Thanks! Happy recovery.

**Comment by davidmartinez10** [comment]
Thank you. You might also want to check this out:

https://github.com/davidmartinez10/bigfloat-esnext
https://unpkg.com/browse/bigfloat-esnext@1.0.2/lib/

It uses native Bigints instead of Chrome Labs JSBI.

**Comment by munrocket** [comment]
Looks like I am too stupid to understand how to add it on page without node.js :D Actually after half of year I am started my own library, but it’s experimental right now.
